package com.dg.mall.pojo;

import java.util.Date;

public class ProductCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.id
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.create_date
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.modify_date
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.orders
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    private Integer orders;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.grade
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.name
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.seo_description
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    private String seoDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.seo_keywords
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    private String seoKeywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.seo_title
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    private String seoTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.tree_path
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    private String treePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.parent
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    private Long parent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.id
     *
     * @return the value of product_category.id
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.id
     *
     * @param id the value for product_category.id
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.create_date
     *
     * @return the value of product_category.create_date
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.create_date
     *
     * @param createDate the value for product_category.create_date
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.modify_date
     *
     * @return the value of product_category.modify_date
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.modify_date
     *
     * @param modifyDate the value for product_category.modify_date
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.orders
     *
     * @return the value of product_category.orders
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.orders
     *
     * @param orders the value for product_category.orders
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.grade
     *
     * @return the value of product_category.grade
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.grade
     *
     * @param grade the value for product_category.grade
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.name
     *
     * @return the value of product_category.name
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.name
     *
     * @param name the value for product_category.name
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.seo_description
     *
     * @return the value of product_category.seo_description
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public String getSeoDescription() {
        return seoDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.seo_description
     *
     * @param seoDescription the value for product_category.seo_description
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public void setSeoDescription(String seoDescription) {
        this.seoDescription = seoDescription == null ? null : seoDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.seo_keywords
     *
     * @return the value of product_category.seo_keywords
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public String getSeoKeywords() {
        return seoKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.seo_keywords
     *
     * @param seoKeywords the value for product_category.seo_keywords
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public void setSeoKeywords(String seoKeywords) {
        this.seoKeywords = seoKeywords == null ? null : seoKeywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.seo_title
     *
     * @return the value of product_category.seo_title
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public String getSeoTitle() {
        return seoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.seo_title
     *
     * @param seoTitle the value for product_category.seo_title
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public void setSeoTitle(String seoTitle) {
        this.seoTitle = seoTitle == null ? null : seoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.tree_path
     *
     * @return the value of product_category.tree_path
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public String getTreePath() {
        return treePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.tree_path
     *
     * @param treePath the value for product_category.tree_path
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public void setTreePath(String treePath) {
        this.treePath = treePath == null ? null : treePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.parent
     *
     * @return the value of product_category.parent
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public Long getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.parent
     *
     * @param parent the value for product_category.parent
     *
     * @mbg.generated Fri Jun 08 09:30:38 GMT+08:00 2018
     */
    public void setParent(Long parent) {
        this.parent = parent;
    }
}