package com.dg.mall.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.modify_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.allocated_stock
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Integer allocatedStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value0
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value1
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value10
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value11
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value12
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value13
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value14
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value15
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value16
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value17
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value18
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value19
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value2
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value3
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value4
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value5
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value6
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value7
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value8
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.attribute_value9
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String attributeValue9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.cost
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private BigDecimal cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.full_name
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.hits
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Long hits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.image
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_gift
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Boolean isGift;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_list
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Boolean isList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_marketable
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Boolean isMarketable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_top
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Boolean isTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.keyword
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.market_price
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private BigDecimal marketPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.memo
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.month_hits
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Long monthHits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.month_hits_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Date monthHitsDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.month_sales
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Long monthSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.month_sales_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Date monthSalesDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.point
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Long point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sales
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Long sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.score
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Float score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.score_count
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Long scoreCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.seo_description
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String seoDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.seo_keywords
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String seoKeywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.seo_title
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String seoTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sn
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stock
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stock_memo
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String stockMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.total_score
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Long totalScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.unit
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.week_hits
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Long weekHits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.week_hits_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Date weekHitsDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.week_sales
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Long weekSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.week_sales_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Date weekSalesDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.weight
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Integer weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.brand
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Long brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.goods
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Long goods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_category
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private Long productCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.introduction
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_date
     *
     * @return the value of product.create_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_date
     *
     * @param createDate the value for product.create_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.modify_date
     *
     * @return the value of product.modify_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.modify_date
     *
     * @param modifyDate the value for product.modify_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.allocated_stock
     *
     * @return the value of product.allocated_stock
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Integer getAllocatedStock() {
        return allocatedStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.allocated_stock
     *
     * @param allocatedStock the value for product.allocated_stock
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAllocatedStock(Integer allocatedStock) {
        this.allocatedStock = allocatedStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value0
     *
     * @return the value of product.attribute_value0
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue0() {
        return attributeValue0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value0
     *
     * @param attributeValue0 the value for product.attribute_value0
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue0(String attributeValue0) {
        this.attributeValue0 = attributeValue0 == null ? null : attributeValue0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value1
     *
     * @return the value of product.attribute_value1
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue1() {
        return attributeValue1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value1
     *
     * @param attributeValue1 the value for product.attribute_value1
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue1(String attributeValue1) {
        this.attributeValue1 = attributeValue1 == null ? null : attributeValue1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value10
     *
     * @return the value of product.attribute_value10
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue10() {
        return attributeValue10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value10
     *
     * @param attributeValue10 the value for product.attribute_value10
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue10(String attributeValue10) {
        this.attributeValue10 = attributeValue10 == null ? null : attributeValue10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value11
     *
     * @return the value of product.attribute_value11
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue11() {
        return attributeValue11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value11
     *
     * @param attributeValue11 the value for product.attribute_value11
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue11(String attributeValue11) {
        this.attributeValue11 = attributeValue11 == null ? null : attributeValue11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value12
     *
     * @return the value of product.attribute_value12
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue12() {
        return attributeValue12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value12
     *
     * @param attributeValue12 the value for product.attribute_value12
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue12(String attributeValue12) {
        this.attributeValue12 = attributeValue12 == null ? null : attributeValue12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value13
     *
     * @return the value of product.attribute_value13
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue13() {
        return attributeValue13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value13
     *
     * @param attributeValue13 the value for product.attribute_value13
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue13(String attributeValue13) {
        this.attributeValue13 = attributeValue13 == null ? null : attributeValue13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value14
     *
     * @return the value of product.attribute_value14
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue14() {
        return attributeValue14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value14
     *
     * @param attributeValue14 the value for product.attribute_value14
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue14(String attributeValue14) {
        this.attributeValue14 = attributeValue14 == null ? null : attributeValue14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value15
     *
     * @return the value of product.attribute_value15
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue15() {
        return attributeValue15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value15
     *
     * @param attributeValue15 the value for product.attribute_value15
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue15(String attributeValue15) {
        this.attributeValue15 = attributeValue15 == null ? null : attributeValue15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value16
     *
     * @return the value of product.attribute_value16
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue16() {
        return attributeValue16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value16
     *
     * @param attributeValue16 the value for product.attribute_value16
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue16(String attributeValue16) {
        this.attributeValue16 = attributeValue16 == null ? null : attributeValue16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value17
     *
     * @return the value of product.attribute_value17
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue17() {
        return attributeValue17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value17
     *
     * @param attributeValue17 the value for product.attribute_value17
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue17(String attributeValue17) {
        this.attributeValue17 = attributeValue17 == null ? null : attributeValue17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value18
     *
     * @return the value of product.attribute_value18
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue18() {
        return attributeValue18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value18
     *
     * @param attributeValue18 the value for product.attribute_value18
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue18(String attributeValue18) {
        this.attributeValue18 = attributeValue18 == null ? null : attributeValue18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value19
     *
     * @return the value of product.attribute_value19
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue19() {
        return attributeValue19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value19
     *
     * @param attributeValue19 the value for product.attribute_value19
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue19(String attributeValue19) {
        this.attributeValue19 = attributeValue19 == null ? null : attributeValue19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value2
     *
     * @return the value of product.attribute_value2
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue2() {
        return attributeValue2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value2
     *
     * @param attributeValue2 the value for product.attribute_value2
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue2(String attributeValue2) {
        this.attributeValue2 = attributeValue2 == null ? null : attributeValue2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value3
     *
     * @return the value of product.attribute_value3
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue3() {
        return attributeValue3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value3
     *
     * @param attributeValue3 the value for product.attribute_value3
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue3(String attributeValue3) {
        this.attributeValue3 = attributeValue3 == null ? null : attributeValue3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value4
     *
     * @return the value of product.attribute_value4
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue4() {
        return attributeValue4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value4
     *
     * @param attributeValue4 the value for product.attribute_value4
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue4(String attributeValue4) {
        this.attributeValue4 = attributeValue4 == null ? null : attributeValue4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value5
     *
     * @return the value of product.attribute_value5
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue5() {
        return attributeValue5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value5
     *
     * @param attributeValue5 the value for product.attribute_value5
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue5(String attributeValue5) {
        this.attributeValue5 = attributeValue5 == null ? null : attributeValue5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value6
     *
     * @return the value of product.attribute_value6
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue6() {
        return attributeValue6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value6
     *
     * @param attributeValue6 the value for product.attribute_value6
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue6(String attributeValue6) {
        this.attributeValue6 = attributeValue6 == null ? null : attributeValue6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value7
     *
     * @return the value of product.attribute_value7
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue7() {
        return attributeValue7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value7
     *
     * @param attributeValue7 the value for product.attribute_value7
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue7(String attributeValue7) {
        this.attributeValue7 = attributeValue7 == null ? null : attributeValue7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value8
     *
     * @return the value of product.attribute_value8
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue8() {
        return attributeValue8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value8
     *
     * @param attributeValue8 the value for product.attribute_value8
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue8(String attributeValue8) {
        this.attributeValue8 = attributeValue8 == null ? null : attributeValue8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.attribute_value9
     *
     * @return the value of product.attribute_value9
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getAttributeValue9() {
        return attributeValue9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.attribute_value9
     *
     * @param attributeValue9 the value for product.attribute_value9
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setAttributeValue9(String attributeValue9) {
        this.attributeValue9 = attributeValue9 == null ? null : attributeValue9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.cost
     *
     * @return the value of product.cost
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.cost
     *
     * @param cost the value for product.cost
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.full_name
     *
     * @return the value of product.full_name
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.full_name
     *
     * @param fullName the value for product.full_name
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.hits
     *
     * @return the value of product.hits
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Long getHits() {
        return hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.hits
     *
     * @param hits the value for product.hits
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setHits(Long hits) {
        this.hits = hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.image
     *
     * @return the value of product.image
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.image
     *
     * @param image the value for product.image
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_gift
     *
     * @return the value of product.is_gift
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Boolean getIsGift() {
        return isGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_gift
     *
     * @param isGift the value for product.is_gift
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setIsGift(Boolean isGift) {
        this.isGift = isGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_list
     *
     * @return the value of product.is_list
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Boolean getIsList() {
        return isList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_list
     *
     * @param isList the value for product.is_list
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setIsList(Boolean isList) {
        this.isList = isList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_marketable
     *
     * @return the value of product.is_marketable
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Boolean getIsMarketable() {
        return isMarketable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_marketable
     *
     * @param isMarketable the value for product.is_marketable
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setIsMarketable(Boolean isMarketable) {
        this.isMarketable = isMarketable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_top
     *
     * @return the value of product.is_top
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Boolean getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_top
     *
     * @param isTop the value for product.is_top
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setIsTop(Boolean isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.keyword
     *
     * @return the value of product.keyword
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.keyword
     *
     * @param keyword the value for product.keyword
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.market_price
     *
     * @return the value of product.market_price
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.market_price
     *
     * @param marketPrice the value for product.market_price
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.memo
     *
     * @return the value of product.memo
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.memo
     *
     * @param memo the value for product.memo
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.month_hits
     *
     * @return the value of product.month_hits
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Long getMonthHits() {
        return monthHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.month_hits
     *
     * @param monthHits the value for product.month_hits
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setMonthHits(Long monthHits) {
        this.monthHits = monthHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.month_hits_date
     *
     * @return the value of product.month_hits_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Date getMonthHitsDate() {
        return monthHitsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.month_hits_date
     *
     * @param monthHitsDate the value for product.month_hits_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setMonthHitsDate(Date monthHitsDate) {
        this.monthHitsDate = monthHitsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.month_sales
     *
     * @return the value of product.month_sales
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Long getMonthSales() {
        return monthSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.month_sales
     *
     * @param monthSales the value for product.month_sales
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setMonthSales(Long monthSales) {
        this.monthSales = monthSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.month_sales_date
     *
     * @return the value of product.month_sales_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Date getMonthSalesDate() {
        return monthSalesDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.month_sales_date
     *
     * @param monthSalesDate the value for product.month_sales_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setMonthSalesDate(Date monthSalesDate) {
        this.monthSalesDate = monthSalesDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.point
     *
     * @return the value of product.point
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Long getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.point
     *
     * @param point the value for product.point
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setPoint(Long point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sales
     *
     * @return the value of product.sales
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Long getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sales
     *
     * @param sales the value for product.sales
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setSales(Long sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.score
     *
     * @return the value of product.score
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.score
     *
     * @param score the value for product.score
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.score_count
     *
     * @return the value of product.score_count
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Long getScoreCount() {
        return scoreCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.score_count
     *
     * @param scoreCount the value for product.score_count
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setScoreCount(Long scoreCount) {
        this.scoreCount = scoreCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.seo_description
     *
     * @return the value of product.seo_description
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getSeoDescription() {
        return seoDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.seo_description
     *
     * @param seoDescription the value for product.seo_description
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setSeoDescription(String seoDescription) {
        this.seoDescription = seoDescription == null ? null : seoDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.seo_keywords
     *
     * @return the value of product.seo_keywords
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getSeoKeywords() {
        return seoKeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.seo_keywords
     *
     * @param seoKeywords the value for product.seo_keywords
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setSeoKeywords(String seoKeywords) {
        this.seoKeywords = seoKeywords == null ? null : seoKeywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.seo_title
     *
     * @return the value of product.seo_title
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getSeoTitle() {
        return seoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.seo_title
     *
     * @param seoTitle the value for product.seo_title
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setSeoTitle(String seoTitle) {
        this.seoTitle = seoTitle == null ? null : seoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sn
     *
     * @return the value of product.sn
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sn
     *
     * @param sn the value for product.sn
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock
     *
     * @return the value of product.stock
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock
     *
     * @param stock the value for product.stock
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock_memo
     *
     * @return the value of product.stock_memo
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getStockMemo() {
        return stockMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock_memo
     *
     * @param stockMemo the value for product.stock_memo
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setStockMemo(String stockMemo) {
        this.stockMemo = stockMemo == null ? null : stockMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.total_score
     *
     * @return the value of product.total_score
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Long getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.total_score
     *
     * @param totalScore the value for product.total_score
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setTotalScore(Long totalScore) {
        this.totalScore = totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.unit
     *
     * @return the value of product.unit
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.unit
     *
     * @param unit the value for product.unit
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.week_hits
     *
     * @return the value of product.week_hits
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Long getWeekHits() {
        return weekHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.week_hits
     *
     * @param weekHits the value for product.week_hits
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setWeekHits(Long weekHits) {
        this.weekHits = weekHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.week_hits_date
     *
     * @return the value of product.week_hits_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Date getWeekHitsDate() {
        return weekHitsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.week_hits_date
     *
     * @param weekHitsDate the value for product.week_hits_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setWeekHitsDate(Date weekHitsDate) {
        this.weekHitsDate = weekHitsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.week_sales
     *
     * @return the value of product.week_sales
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Long getWeekSales() {
        return weekSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.week_sales
     *
     * @param weekSales the value for product.week_sales
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setWeekSales(Long weekSales) {
        this.weekSales = weekSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.week_sales_date
     *
     * @return the value of product.week_sales_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Date getWeekSalesDate() {
        return weekSalesDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.week_sales_date
     *
     * @param weekSalesDate the value for product.week_sales_date
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setWeekSalesDate(Date weekSalesDate) {
        this.weekSalesDate = weekSalesDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.weight
     *
     * @return the value of product.weight
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.weight
     *
     * @param weight the value for product.weight
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.brand
     *
     * @return the value of product.brand
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Long getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.brand
     *
     * @param brand the value for product.brand
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setBrand(Long brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.goods
     *
     * @return the value of product.goods
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Long getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.goods
     *
     * @param goods the value for product.goods
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setGoods(Long goods) {
        this.goods = goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_category
     *
     * @return the value of product.product_category
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public Long getProductCategory() {
        return productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_category
     *
     * @param productCategory the value for product.product_category
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setProductCategory(Long productCategory) {
        this.productCategory = productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.introduction
     *
     * @return the value of product.introduction
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.introduction
     *
     * @param introduction the value for product.introduction
     *
     * @mbg.generated Thu Jun 07 14:36:17 GMT+08:00 2018
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}